#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:f
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: literature
#+date: <2022-03-16 Wed>
#+author: Andrew M Davis, Greg Linden
#+email: @reconmaster:matrix.org; @gswhiz:matrix.org
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.2 (Org mode 9.4.6)
#+cite_export:
* Introduction
Reading allows one to absorb knowledge that has been transmitted
across time. Here we try to curate some reading recommendations that
provide information that could help cultivate a global state of Peace.
* Biography
** Frederick Douglass
*** [[https://gutenberg.org/files/23/23-h/23-h.htm][Narrative of the Life of Frederick Douglass]]
** Martin Meredith
*** [[https://archive.org/details/unset0000unse_s4e8/page/n5/mode/2up][Nelson Mandela: a biography]]
* Economics/Finance
** [[https://en.wikipedia.org/wiki/Peter_Kropotkin][Peter Kropotkin]]
*** [[https://en.wikipedia.org/wiki/Mutual_Aid:_A_Factor_of_Evolution][Mutual Aid: A Factor of Evolution]]
** [[https://en.wikipedia.org/wiki/Bernie_Sanders][Bernie Sanders]]
*** [[https://en.wikipedia.org/wiki/It%27s_OK_to_Be_Angry_About_Capitalism][It's OK to Be Angry About Capitalism]]
* Fiction
** [[https://en.wikipedia.org/wiki/George_Orwell][George Orwell]]
*** [[https://en.wikipedia.org/wiki/Nineteen_Eighty-Four][Nineteen Eighty-Four]]
 Non-Fiction
** [[https://en.wikipedia.org/wiki/Marcus_Aurelius][Marcus Aurelius]]
*** [[https://en.wikipedia.org/wiki/Meditations][Meditations]]
** [[https://en.wikipedia.org/wiki/Joseph_Campbell][Joseph Campbell]]
*** [[https://en.wikipedia.org/wiki/The_Hero_with_a_Thousand_Faces][The Hero with a Thousand Faces]]
Influential on George Lucas and his [[https://en.wikipedia.org/wiki/Star_Wars][Star Wars]] films.
** [[https://en.wikipedia.org/wiki/Hillary_Clinton][Hillary Clinton]]
*** [[https://en.wikipedia.org/wiki/State_of_Terror][State of Terror]]
** [[https://en.wikipedia.org/wiki/Buckminster_Fuller][Buckminster Fuller]]
- [[https://en.wikipedia.org/wiki/Operating_Manual_for_Spaceship_Earth][Operating Manual for Spaceship Earth]]
** Kajal Odedra
*** [[https://www.kajalodedra.com/][Do Something: Activism for Everyone]]
This is a good resource for how to become an activist for something
you are passionate about.
** [[https://en.wikipedia.org/wiki/Robert_M._Pirsig][Robert M. Pirsig]]
- [[https://en.wikipedia.org/wiki/Zen_and_the_Art_of_Motorcycle_Maintenance][Zen and the Art of Motorcycle Maintenance]]
* Political
** [[https://en.wikipedia.org/wiki/Bob_Woodward][Bob Woodward]]
*** [[https://en.wikipedia.org/wiki/Rage_(Woodward_book)][Rage]]
** Stuart Stevens
*** [[https://www.penguinrandomhouse.com/books/623807/it-was-all-a-lie-by-stuart-stevens/][It Was All a Lie]]
* Society
** The Vision of Race Unity
- pamphlet
- p. 8 “The responsibility for the achievement of racial peace and
  unity in the US rests upon both Black and White Americans. To build
  a society in which the rights of all its members are respected and
  guaranteed, both races must be animated with the spirit of optimism
  and faith in the eventual realization of their highest aspirations.
  Neither White nor Black Americans should assume that the
  responsibility for the elimination of prejudice and of its effects
  belongs exclusively to the other Both must recognize that unity s
  essential for their common survival. Both must recognize there is
  only one human species.”
- p. 10 “Both groups must understand that no real change will come
  about without close association, fellowship, and friendship among
  diverse people. Diversity of color, nationality, and culture
  enhances the human experience and should never be made a barrier to
  harmonious relationships, to friendship, or to marriage.”
** [[https://www.kaitlincurtice.com/books/][Kitlin B Curtice]]
*** Living Resistance
Living Resistance An Indigenous Vision for Seeking Wholeness Every
Day, Kaitlin B. Curtice, Brazos Press, 2023 The book is filled with
personal and societal wisdom. One small quote that I like: “Rebellion
is as much of a cage as obedience is. They both mean living in
reaction to someone else’s way instead of forging your own. Freedom is
not being for or against an ideal, but creating your own existence
from scratch.” Glennon Doyle, Untamed
* Self-help
** [[https://en.wikipedia.org/wiki/Richard_Nelson_Bolles][Richard Nelson Bolles]]
*** [[https://en.wikipedia.org/wiki/What_Color_Is_Your_Parachute%3F][What Color Is Your Parachute?]]
How To Find Your Mission in Life. A quite famous book on seeking
career and life choices as one ages.
** Arthur Brooks
*** [[https://arthurbrooks.com/from-strength-to-strength][From Strength to Strength]]
#+begin_quote
Use things.
Love people.
Worship the divine.
#+end_quote
A very useful book on finding your own path during the second half of
your life. The book is filled with helpful advice on how to manage
your transition from working to living into retirement with purpose
and motivation. These 7 words sum it up.
** Michael A Singer
*** The Untethered Soul
"the journey beyond yourself"

A powerful book that describes itself this way: “…begins by walking
you through your relationship with your thoughts and emotions,…It then
delves into what you can do to free yourself from habitual thoughts,
emotions, and energy patterns that limit your consciousness.” Chapter
19 titled The Loving Eyes of God encourages inward meditation to have
direct experience of the Divine.
* Spirituality
** [[https://en.wikipedia.org/wiki/Bah%C3%A1%CA%BC%C3%AD_Faith][Baháʼí]]
*** [[https://www.bahaibookstore.com/Peace-For-Our-Planet-P8829.aspx][Peace For Our Planet]]
- a book to give to those who join us as a peace primer & history
- Ideas that it evoked: UN’s Millennium Goals, the World Court & ICC
  in The Hague. The Peace Palace.
*** Rainn Wilson
**** [[https://www.soulboom.com/][Soul Boom]]
*** [[https://www.bahaibookstore.com/Toward-Oneness-and-Freedom-from-Racial-Prejudice-P10179.aspx][Toward Oneness & Freedom from Racial Prejudice]]
- p. 25 #25: “Shut your eyes to estrangement, then fix your gaze upon
  unity. Cleave tenaciously unto that which will lead to the
  well-being and tranquility of all mankind. This span of earth is but
  one homeland and one habitation. It behoveth you to abandon
  vainglory which causeth alienation and to set your hearts on
  whatever will ensure harmony.”
- p. 88 #118: “The perpetuation of ignorance is a most grievous form
  of oppression; it reinforces the many walls of prejudice that stand
  as barriers to the realization of the oneness of humankind…Access to
  knowledge is the right of every human being….”
** Zen
*** [[https://en.wikipedia.org/wiki/Shunry%C5%AB_Suzuki][Shunryū Suzuki]]
**** [[https://en.wikipedia.org/wiki/Zen_Mind%2C_Beginner's_Mind][Zen Mind, Beginner's Mind]]
